version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file: 
      - ./docker/server/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/server:/server:z
    stdin_open: true
    tty: true
  pg:
    build:
      context: .
      dockerfile: ./docker/pg/Dockerfile
    env_file: 
      - ./docker/pg/.env.development
    restart: on-failure
    volumes:
      - ${PWD}/tmp/pg:/bitnami/postgresql